### ISSUE TITLE
Error with transfering files to nodes

### ISSUE THREAD

**Issue by nj-kore** [axelniklasson/plcli#6]
For the scripts provision and health-check, and the file transfer does not seem to work.  
```
plcli provision ./provision.sh cse-white.cse.chalmers.se
Initiaing provisioning of 1 node(s)
Provision of node cse-white.cse.chalmers.se started by worker 0!
Could not transfer provision script to node cse-white.cse.chalmers.se. Error: scp: ~/provision.sh: No such file or directory
Nodes provisioned!
```
I have created the file ~/provision.sh, but the error seems to be on the remote computer.
If we perform the transfer command manually, the file transfer works.

One thing to explore would be to change

`err := Transfer(options.Slice, hostname, scriptPath, "~/provision.sh")`

to

`err := Transfer(options.Slice, hostname, scriptPath, "provision.sh")`

**Comment by axelniklasson** [comment]
Seems changing to `err := Transfer(options.Slice, hostname, scriptPath, "provision.sh")` works -- will publish a fix today! Thanks!

```
➜  plcli git:(dev) go run plcli.go provision ./provision.sh cse-white.cse.chalmers.se
2021/12/08 16:49:22 Initiaing provisioning of 1 node(s)
2021/12/08 16:49:22 Provision of node cse-white.cse.chalmers.se started by worker 0!
2021/12/08 16:49:23 Successfully transferred ./provision.sh to cse-white.cse.chalmers.se:provision.sh
2021/12/08 16:49:23 Executing "cd; chmod +x provision.sh; sh provision.sh" on cse-white.cse.chalmers.se
2021/12/08 16:49:23 Executing "cd; rm provision.sh" on cse-white.cse.chalmers.se
2021/12/08 16:49:23 Provision of node cse-white.cse.chalmers.se done!
2021/12/08 16:49:23 Nodes provisioned!
```

**Comment by axelniklasson** [comment]
@nj-kore this is fixed and published now, thanks for reporting!
